apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    ksonnet.io/component: my-paddle-operator
  name: paddlejobs.paddlepaddle.org
spec:
  group: paddlepaddle.org
  names:
    kind: PaddleJob
    plural: paddlejobs
    singular: paddlejob
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            paddleReplicaSpecs:
              properties:
                pserver:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
                trainer:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
  version: v1
